name: hdb-predictor-app-env 
channels:
  - conda-forge
  - defaults  
dependencies:
  - python=3.13
  - pandas
  - numpy
  - scikit-learn
  - xgboost           
  - lightgbm
  - shap
  - joblib
  - matplotlib
  - streamlit
  - pip
  - pip:
      - requests