name: hdb-price-predictor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - scikit-learn
  - xgboost           
  - lightgbm
  - shap
  - matplotlib
  - streamlit
  - pip
  - pip:
      - requests